#!/bin/sh
# read our configuration
source /boot/config/plugins/shellinabox-plugin/shellinabox-plugin.cfg

prog="shellinaboxd"
SHELLINABOXD="/usr/sbin/$prog"
LOCKFILE="/var/lock/$prog"
PIDFILE="/var/run/$prog.pid"
STYLES="/usr/local/emhttp/plugins/shellinabox-plugin/styles"
CONFIG="/boot/config/plugins/shellinabox-plugin"
USER_CSS="Color:+$STYLES/color.css,Monochrome:-$STYLES/monochrome.css;White:+$STYLES/white-on-black.css,Black:-$STYLES/black-on-white.css,Blue:-$STYLES/blue-on-black.css,Green:-$STYLES/green-on-black.css,Pink:-$STYLES/pink-on-black.css,Purple:-$STYLES/purple-on-black.css,Red:-$STYLES/red-on-black.css,Yellow:-$STYLES/yellow-on-black.css"

# no-op if already running
if [ ! -r $PIDFILE ]; then
sleep 1
nohup /usr/sbin/$prog --user=$RUNAS --background=$PIDFILE --port=$PORT --cert=$CONFIG --user-css=$USER_CSS > /dev/null 2>&1 | logger -tshellinaboxd &
touch $LOCKFILE
TIMER=0
while [ ! -e $PIDFILE ]; do
	sleep 1
	let TIMER=$TIMER+1
      if [ $TIMER -gt 5 ]; then
           echo -n "$PIDFILE not created"
           break
     	fi
done
fi